% -*- mode: noweb; noweb-default-code-mode: R-mode; -*-
\documentclass{article}

%headers and footers
\usepackage{fancyhdr}
\setlength{\headheight}{15pt}
\pagestyle{fancyplain}
\lhead{\fancyplain{}{\thepage}}
\chead{}
\rhead{\fancyplain{}{\bfseries miRNA sequence file basics}}
\rfoot{$Rev: 2964 $}
\cfoot{}
\lfoot{\includegraphics[width=0.1\textwidth]{/nas/is1/leipzig/src/R/bicLogo.png}\\[1cm]}


%hyperlink setup
\usepackage{hyperref}
\usepackage{xcolor}
\definecolor{dark-red}{rgb}{0.4,0.15,0.15}
\definecolor{dark-blue}{rgb}{0.15,0.15,0.4}
\definecolor{medium-blue}{rgb}{0,0,0.5}
\hypersetup{
    colorlinks, linkcolor={dark-red},
    citecolor={dark-blue}, urlcolor={medium-blue}
}


\usepackage{longtable}
\usepackage{rotating}

%underscores in variable names cause problems
%\usepackage{underscore}

\begin{document}
\newcommand{\COT}{C$_{0}$t }
\title{Sequence File Basic Information}
\author{Jeremy Leipzig}
\maketitle
\tableofcontents
\pagebreak
<<setup,echo=FALSE,results=hide>>=
library(Rsamtools)
library(Biostrings)
library(stringr)
library(plyr)
library(reshape)
#library("edgeR")
library("DESeq")
library(ggplot2)
library(xtable)

sessInfo<-sessionInfo()


library("GenomicFeatures")
knownGenes<-makeTranscriptDbFromUCSC(
genome="hg19",
tablename="knownGene",
transcript_ids=NULL,
circ_seqs=DEFAULT_CIRC_SEQS,
url="http://genome.ucsc.edu/cgi-bin/",
goldenPath_url="http://hgdownload.cse.ucsc.edu/goldenPath")
GR <- transcripts(knownGenes)
reference<-"hg19"
alignmentStringency<-"tight"
bamDirectory<-concat("/bam",aligner,alignmentStringency,reference,alignmentStrategy,"/",sep="/")
configFile<-'/nas/is1/leipzig/src/R/dirConfig.R'
source(configFile)
setwd("/nas/is1/leipzig")
bfl <- BamFileList(bamPaths)
olap <- summarizeOverlaps(GR, bfl)

@
\section{FASTQ}
\subsection{IIfx}
Twelve samples, three cohorts of normal and retinoblastoma tissues were collected for miRNA sequencing using the Illumina IIfx, Illumina HiSeq, and Ion Torrent PGM
\subsection{HiSeq}

\subsection{PGM}

\section{Alignments}
\subsection{NovoDefault}
\subsection{Randomly Assigned}
\subsection{Unique}